service: serverless-api
frameworkVersion: '3'

useDotenv: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs18.x
  region: 'us-east-1'

functions:
  api:
    handler: ./src/functions/index.handler
    events:
      - httpApi: '*'
